---

- name: Install httpd
  yum:
    name: "{{ package }}"
    state: present

- name: get the machine hostname
  command: hostname -i
  register: hostname

- name: Update the config file
  replace:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  with_items:
  - { regexp: 'Listen 80', replace: 'Listen {{ hostname.stdout_lines[0] }}:80'}
- copy: src=index.html dest=/var/www/html mode=0755
- service: name=httpd state=started
